services:
  db:
    image: postgres:18
    container_name: clothing_store_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: clothing_store
      POSTGRES_PASSWORD: clothing_store
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U clothing_store -d postgres"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  postgres_data:
